version: '3.8'

services:
  telebot:
    container_name: telebot
    build:
      context: .
      dockerfile: Dockerfile
    image: telebot-docker
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      DOCKER: True
    networks:
      - telebot-network

networks:
  telebot-network:
    driver: bridge