version: '3.8'

services:
  telebot:
    container_name: telebot
    build:
      context: .
      dockerfile: Dockerfile
    image: telebot-docker
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    environment:
      DOCKER: True
    networks:
      - telebot-network

networks:
  telebot-network:
    driver: bridge