version: '3.8'

services:
  telebot:
    container_name: telebot
    build:
      context: .
      dockerfile: Dockerfile
    image: telebot-docker
    command: sleep 2 && warp-svc>/dev/null &  sleep 3 && warp-cli --accept-tos connect  
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    environment:
      DOCKER: True
    networks:
      - telebot-network

networks:
  telebot-network:
    driver: bridge