PROGRESS_FREQUENCY=10
PARALLEL_DOWNLOADS=8
CONFIG_FILE="telebot.cnf"
SESSION="telebot"
MOVIES_FILE_PATH = 'movies.txt'
TV_SHOWS_FILE_PATH = 'tv_shows.txt'
TELEGRAM_DAEMON_SESSION_PATH=''
PASS2fA='Acc#3157'